### ISSUE TITLE
PA Review: Heroku Hosting & User Auth

### ISSUE THREAD

**Issue by kliewUS** [kliewUS/Todollo#2]
### Heroku Hosting
- [x] [Site](https://todollo.herokuapp.com/#/) is currently online on Heroku with no bugs.

### User Auth
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by ryan-mapa** [comment]
Very clean styling
